### Register New User
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "full_name": "John Doe",
    "username": "johndoess",
    "password": "Password1*",
    "email": "john@example.com"
}

### Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "johndoess",
    "password": "Password1*"
}

### Get Server
GET http://localhost:8080/api/v1/

### Remove User
DELETE http://localhost:8080/api/v1/remove/5

