### Register New User
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "full_name": "Faris Munir Mahdi",
    "username": "farismunir",
    "email": "farismunir2@gmail.com",
    "password": "Password1*"
}

### Login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "username": "farismunir",
    "password": "Password1*"
}

### Reset Password
PATCH http://localhost:8080/api/v1/reset
Content-Type: application/json

{
    "email": "johns@example.com",
    "password": "Password1*"
}

### Send OTP
POST http://localhost:8080/api/v1/otp/send
Content-Type: application/json

{
    "email": "farismunir2@gmail.com"
}

### Verify OTP
POST http://localhost:8080/api/v1/otp/verify/26
Content-Type: application/json

{
    "otp_code": "335938"
}

### Request API
POST http://localhost:8080/api/v1/request/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcmlzbXVuaXIiLCJyb2xlIjoidXNlciIsInN0YXR1cyI6ImFjdGl2ZSIsImV4cCI6MTcxOTE2NjAwNCwiaWF0IjoxNzE4OTA2ODA0LCJpc3MiOiJBc2tJTiEifQ.oxFjW5JyFcui0VOWMSimvhHEHU7WD41bke7-PxHl5PA
Content-Type: application/json

{
    "message": "Buatlah sebuah program Go, Clean Architecture, dan Gin!"
}

### Logout
DELETE http://localhost:8080/api/v1/logout/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcmlzbXVuaXIiLCJyb2xlIjoidXNlciIsInN0YXR1cyI6ImFjdGl2ZSIsImV4cCI6MTcxOTE2NTQzMywiaWF0IjoxNzE4OTA2MjMzLCJpc3MiOiJBc2tJTiEifQ.DvAfJJKPSRoECxBUE2kuH_SnALlMhOl1Tuz6DyUEyRc

### Get Server
GET http://localhost:8080/api/v1/

### Remove User
DELETE http://localhost:8080/api/v1/remove/28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhcmlzbXVuaXIiLCJyb2xlIjoidXNlciIsImV4cCI6MTcxOTExNjQ4MywiaWF0IjoxNzE4ODU3MjgzLCJpc3MiOiJBc2tJTiJ9.sEUV3-G5OaMRA4dmBJcUoj-SGDHwzWQN9NwNh0OkBYU
